include ./themes.conf
background_opacity 0.7
# background_blur 500


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
# END_KITTY_FONTS


# Tabs settings
tab_bar_style slant
tab_bar_min_tabs 2
# tab_activity_symbol 󰐾
tab_title_template "{index} 󰄰:{title}"
active_tab_title_template "{index} 󰐾:{title}"
