# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable Mouse Support
set -g mouse on

# Increase History Limit
set -g history-limit 50000

# True Color Support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# tmux cursor style
set -g cursor-style "blinking-bar"

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

#status line customization
set -g status-style bg=#385D70
# set -ag status-style fg=#2A3033

# windows customization
set -g window-status-style bg="#196a93",fg="#909090" 
set -g window-status-current-style bg="#00A2F0",fg="#f0ffff"

# orange = '#F08500'
# color_orange = '#d65d0e'
# color_purple = '#b16286'

# set -g status-left
# set -g window_active "󰄰"

set -g window-status-current-format 	"#[fg=#00A2F0, bg=#385D70 ]#[fg=default, bg=default]#I#{?window_active, 󰐾, 󰄰}: #{window_name} #[fg=#00A2F0, bg=#385D70 ]"
set -g window-status-format 		"#[fg=#196a93, bg=#385D70 ]#[fg=default, bg=default]#I#{?window_active, 󰐾, 󰄰}: #{window_name} #[fg=#196a93, bg=#385D70 ]"

# right side of the status line config
# the og version
# set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:pane_title}\" %H:%M %d-%b-%y"
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}#[fg=#F08500, bg=default]#[fg=default, bg=#F08500] #{b:pane_current_path} #[fg=#d65d03, bg=#F08500]#[bg=#d65d0e, fg=default]%H:%M %d-%b-%y"


# set -g pane-status-format "#P:#{?window_active, 󰐾,󰄰 }[#T]"
# set -g window-pane-status-format "#P:#{?window_active, 󰐾,󰄰 }[#T]"
# set -g window-pane-status-format "#P:#{?window_active, 󰐾,󰄰 }[#T]"
# set -g window-pane-status-format "#P:#{?window_active, 󰐾,󰄰 }[#T]"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
