# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu =  rofi -show combi -combi-modes "filebrowser,drun,ssh" -modes combi
$browser = flatpak run app.zen_browser.zen


$mainMod = SUPER # Sets "Windows" key as main modifier

