splash = false
ipc = true
preload = /home/noriyaki/Desktop/fluid/Caves_google_pixel_stock-High_Quality_HD_Wallpaper Wallpaper_1920x1080[10wallpaper.com].jpg
wallpaper = DP-1,/home/noriyaki/Desktop/fluid/Caves_google_pixel_stock-High_Quality_HD_Wallpaper Wallpaper_1920x1080[10wallpaper.com].jpg
