# $mainMod = SUPER # Sets "Windows" key as main modifier
# $terminal = kitty # default terminal

source = ~/.config/hypr/default.conf
#$lock = hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf
$lock = swaylock -C ~/.config/hypr/swaylock.conf

# clipse keybind
bind = SUPER, V, exec, $terminal --class clipse -e 'clipse'

# Move active window to a next/previous workspace mainMod + pgUp/pgDown
bind = $mainMod Shift, Page_Up, movetoworkspace, e-1
bind = $mainMod Shift, Page_Down, movetoworkspace, e+1


# move to workspace prev/next
bind = $mainMod, Page_Up, workspace, e-1
bind = $mainMod, Page_Down, workspace, e+1

# Move active window in a direction (like window snapping in DE)
bind = $mainMod Shift, up, movewindow, u
bind = $mainMod Shift, down, movewindow, d
bind = $mainMod Shift, left, movewindow, l
bind = $mainMod Shift, right, movewindow,


# Cycle between windows within the same workspace
bind = $mainMod, Tab, cyclenext
#bind = $mainMod SHIFT, Tab, cycleprev
# screenshots
bind = , Print, exec, grim -g "$(slurp -d)" - | wl-copy

# Lock screen
bind = $mainMod, L, exec, $lock
