# Window rules set by User


# floating window for clipse
windowrulev2 = float,class:(clipse) # ensure you have a floating window class set if you want this behavior
windowrulev2 = size 622 652,class:(clipse) # set the size of the window as necessary

# floating window for PiP in browsers
    windowrulev2 = float, title:(Picture-in-Picture)
    windowrulev2 = persistentsize, title:(Picture-in-Picture),floating:1
    windowrulev2 = move onscreen 100%-20,title:(Picture-in-Picture)

# floating window for kde sharing prompt
    windowrulev2 = float, title:(Send File — Dolphin)
    windowrulev2 = float, title:(KDE Connect)
    windowrulev2 = persistentsize, title:(KDE Connect)


# separate workspace for minecraft and Modrinth
    windowrulev2 = workspace name:MC,class:^(Minecraft).*
    windowrulev2 = maximize, class:^(Minecraft).*
    windowrulev2 = maximize, class:(modrinth-app-wrapped)
    windowrulev2 = workspace name:MC,class:(modrinth-app-wrapped)

# new workspace of browser
    windowrule = workspace name:web,class:(app.zen_browser.zen)
    windowrulev2 = maximize, class:(app.zen_browser.zen)
